import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import { reportError } from '@williamthorsen/nmr-core';
import { stringify } from 'yaml';

import { CONFIG_FILE_PATH, loadConfig } from '../loadConfig.ts';
import type { RepoLabelsConfig } from '../types.ts';
import { validateConfig } from '../validateConfig.ts';
import { hashPresetFile } from './presets.ts';
import { resolveLabels } from './resolveLabels.ts';
import { checkRetiredSyncLabelsConfig } from './retiredConfig.ts';
import type { LabelDefinition } from './types.ts';

/** Output path for the generated labels file. */
export const LABELS_OUTPUT_PATH = '.github/labels.yaml';

/** Format resolved labels as YAML with generated header including preset hashes. */
export function formatLabelsYaml(labels: LabelDefinition[], presetHashes: Map<string, string>): string {
  const headerLines = ['# Generated by release-kit sync-labels — do not edit.', `# Source: ${CONFIG_FILE_PATH}`];
  // eslint-disable-next-line unicorn/no-array-sort -- spread already creates a fresh copy
  for (const [name, hash] of [...presetHashes].sort(([a], [b]) => a.localeCompare(b))) {
    headerLines.push(`# ${name} preset hash: ${hash}`);
  }

  // Use single quotes when quoting is needed; let yaml decide when to quote; disable line wrapping
  const yamlBody = stringify(labels, { singleQuote: true, lineWidth: 0 });
  return headerLines.join('\n') + '\n' + yamlBody;
}

/**
 * Load `.config/release-kit.config.ts` and return its `repoLabels` block.
 *
 * Reports an actionable error and returns `undefined` when the config file is missing,
 * fails to load or validate, or carries no `repoLabels` block.
 */
export async function loadRepoLabelsConfig(): Promise<RepoLabelsConfig | undefined> {
  let raw: unknown;
  try {
    raw = await loadConfig();
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    reportError(`Failed to load config: ${message}`);
    return undefined;
  }

  if (raw === undefined) {
    reportError(`No config file found at ${CONFIG_FILE_PATH}. Run \`release-kit sync-labels init\` first.`);
    return undefined;
  }

  const { config, errors } = validateConfig(raw);
  if (errors.length > 0) {
    process.stderr.write('Invalid config:\n');
    for (const err of errors) {
      process.stderr.write(`  ❌ ${err}\n`);
    }
    return undefined;
  }

  if (config.repoLabels === undefined) {
    reportError(
      `No \`repoLabels\` block found in ${CONFIG_FILE_PATH}. Run \`release-kit sync-labels init\` to seed one.`,
    );
    return undefined;
  }

  return config.repoLabels;
}

/** Options for the `sync-labels generate` subcommand. */
interface GenerateOptions {
  /** Compare the regenerated content against the committed file instead of writing. */
  check?: boolean;
}

/**
 * Run the `sync-labels generate` command.
 *
 * Loads the `repoLabels` block from `.config/release-kit.config.ts`, resolves presets and
 * label adjustments, and writes `.github/labels.yaml` — or, with `check`, regenerates in
 * memory and reports whether the committed file is stale, writing nothing. Returns 0 on
 * success, 1 on failure.
 */
export async function generateCommand({ check = false }: GenerateOptions = {}): Promise<number> {
  if (checkRetiredSyncLabelsConfig()) {
    return 1;
  }

  const repoLabels = await loadRepoLabelsConfig();
  if (repoLabels === undefined) {
    return 1;
  }

  let labels;
  try {
    labels = resolveLabels(repoLabels);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    reportError(`Failed to resolve labels: ${message}`);
    return 1;
  }

  const presetHashes = new Map<string, string>();
  for (const presetName of repoLabels.extends ?? []) {
    presetHashes.set(presetName, hashPresetFile(presetName));
  }

  const content = formatLabelsYaml(labels, presetHashes);

  if (check) {
    return compareAgainstCommittedFile(content);
  }

  try {
    mkdirSync(dirname(LABELS_OUTPUT_PATH), { recursive: true });
    writeFileSync(LABELS_OUTPUT_PATH, content, 'utf8');
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    reportError(`Failed to write ${LABELS_OUTPUT_PATH}: ${message}`);
    return 1;
  }

  console.info(`Generated ${LABELS_OUTPUT_PATH} with ${String(labels.length)} labels.`);
  return 0;
}

/** Compare regenerated content against the committed labels file; report and return an exit code. */
function compareAgainstCommittedFile(expected: string): number {
  let existing: string;
  try {
    existing = readFileSync(LABELS_OUTPUT_PATH, 'utf8');
  } catch {
    reportError(`${LABELS_OUTPUT_PATH} is missing. Run \`release-kit sync-labels generate\` and commit the result.`);
    return 1;
  }

  if (existing !== expected) {
    reportError(`${LABELS_OUTPUT_PATH} is stale. Run \`release-kit sync-labels generate\` and commit the result.`);
    return 1;
  }

  console.info(`${LABELS_OUTPUT_PATH} is up to date.`);
  return 0;
}
