import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import { dump } from 'js-yaml';

import { loadSyncLabelsConfig, SYNC_LABELS_CONFIG_PATH } from './loadSyncLabelsConfig.ts';
import { resolveLabels } from './resolveLabels.ts';
import type { LabelDefinition } from './types.ts';

/** Output path for the generated labels file. */
export const LABELS_OUTPUT_PATH = '.github/labels.yaml';

/** Header comment prepended to the generated labels file. */
const GENERATED_HEADER = `# Generated by release-kit sync-labels — do not edit.
# Source: ${SYNC_LABELS_CONFIG_PATH}
`;

/** Format resolved labels as YAML with the generated header comment. */
export function formatLabelsYaml(labels: LabelDefinition[]): string {
  // Use double quotes when quoting is needed; let js-yaml decide when to quote; disable line wrapping
  const yamlBody = dump(labels, { quotingType: '"', forceQuotes: false, lineWidth: -1 });
  return GENERATED_HEADER + yamlBody;
}

/**
 * Run the `sync-labels generate` command.
 *
 * Loads the sync-labels config, resolves presets and custom labels, and writes `.github/labels.yaml`.
 * Returns 0 on success, 1 on failure.
 */
export async function generateCommand(): Promise<number> {
  let config;
  try {
    config = await loadSyncLabelsConfig();
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`Error loading config: ${message}`);
    return 1;
  }

  if (config === undefined) {
    console.error(`No config file found at ${SYNC_LABELS_CONFIG_PATH}. Run \`release-kit sync-labels init\` first.`);
    return 1;
  }

  let labels;
  try {
    labels = resolveLabels(config);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`Error resolving labels: ${message}`);
    return 1;
  }

  const content = formatLabelsYaml(labels);

  try {
    mkdirSync(dirname(LABELS_OUTPUT_PATH), { recursive: true });
    writeFileSync(LABELS_OUTPUT_PATH, content, 'utf8');
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`Error writing ${LABELS_OUTPUT_PATH}: ${message}`);
    return 1;
  }

  console.info(`Generated ${LABELS_OUTPUT_PATH} with ${String(labels.length)} labels.`);
  return 0;
}
