import { afterEach, describe, expect, it, vi } from 'vitest';

import type { LabelDefinition } from '../types.ts';

const mockLoadSyncLabelsConfig = vi.hoisted(() => vi.fn());
const mockResolveLabels = vi.hoisted(() => vi.fn());
const mockMkdirSync = vi.hoisted(() => vi.fn());
const mockWriteFileSync = vi.hoisted(() => vi.fn());

vi.mock(import('../loadSyncLabelsConfig.ts'), async (importOriginal) => {
  const original = await importOriginal();
  return { ...original, loadSyncLabelsConfig: mockLoadSyncLabelsConfig };
});

vi.mock(import('../resolveLabels.ts'), () => ({
  resolveLabels: mockResolveLabels,
}));

vi.mock(import('node:fs'), () => ({
  mkdirSync: mockMkdirSync,
  writeFileSync: mockWriteFileSync,
}));

import { formatLabelsYaml, generateCommand, LABELS_OUTPUT_PATH } from '../generateCommand.ts';

describe(generateCommand, () => {
  afterEach(() => {
    mockLoadSyncLabelsConfig.mockReset();
    mockResolveLabels.mockReset();
    mockMkdirSync.mockReset();
    mockWriteFileSync.mockReset();
    vi.restoreAllMocks();
  });

  it('returns 1 when no config file is found', async () => {
    mockLoadSyncLabelsConfig.mockResolvedValue(undefined);
    const spy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    const exitCode = await generateCommand();

    expect(exitCode).toBe(1);
    expect(spy).toHaveBeenCalledWith(expect.stringContaining('No config file found'));
  });

  it('returns 1 when config loading throws', async () => {
    mockLoadSyncLabelsConfig.mockRejectedValue(new Error('parse failure'));
    const spy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    const exitCode = await generateCommand();

    expect(exitCode).toBe(1);
    expect(spy).toHaveBeenCalledWith(expect.stringContaining('parse failure'));
  });

  it('returns 1 when label resolution throws', async () => {
    mockLoadSyncLabelsConfig.mockResolvedValue({ presets: ['common'] });
    mockResolveLabels.mockImplementation(() => {
      throw new Error('Label name collision');
    });
    const spy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    const exitCode = await generateCommand();

    expect(exitCode).toBe(1);
    expect(spy).toHaveBeenCalledWith(expect.stringContaining('Label name collision'));
  });

  it('writes labels file and returns 0 on success', async () => {
    const labels: LabelDefinition[] = [{ name: 'bug', color: 'd73a4a', description: "Something isn't working" }];
    mockLoadSyncLabelsConfig.mockResolvedValue({ presets: ['common'] });
    mockResolveLabels.mockReturnValue(labels);
    vi.spyOn(console, 'info').mockImplementation(() => undefined);

    const exitCode = await generateCommand();

    expect(exitCode).toBe(0);
    expect(mockMkdirSync).toHaveBeenCalledWith('.github', { recursive: true });
    expect(mockWriteFileSync).toHaveBeenCalledWith(
      LABELS_OUTPUT_PATH,
      expect.stringContaining('Generated by release-kit'),
      'utf8',
    );
  });

  it('returns 1 when file writing fails', async () => {
    mockLoadSyncLabelsConfig.mockResolvedValue({ presets: ['common'] });
    mockResolveLabels.mockReturnValue([]);
    mockMkdirSync.mockImplementation(() => {
      throw new Error('EACCES');
    });
    const spy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    const exitCode = await generateCommand();

    expect(exitCode).toBe(1);
    expect(spy).toHaveBeenCalledWith(expect.stringContaining('EACCES'));
  });
});

describe(formatLabelsYaml, () => {
  it('includes the generated header comment', () => {
    const labels: LabelDefinition[] = [{ name: 'bug', color: 'd73a4a', description: "Something isn't working" }];

    const result = formatLabelsYaml(labels);

    expect(result).toContain('# Generated by release-kit sync-labels');
    expect(result).toContain('# Source: .config/sync-labels.config.ts');
  });

  it('produces valid YAML label entries', () => {
    const labels: LabelDefinition[] = [
      { name: 'bug', color: 'd73a4a', description: "Something isn't working" },
      { name: 'feature', color: '0075ca', description: 'New feature' },
    ];

    const result = formatLabelsYaml(labels);

    expect(result).toContain('- name: bug');
    expect(result).toContain('  color: d73a4a');
    expect(result).toContain('- name: feature');
  });

  it('produces stable output for the same input', () => {
    const labels: LabelDefinition[] = [
      { name: 'bug', color: 'd73a4a', description: 'Bug' },
      { name: 'feature', color: '0075ca', description: 'Feature' },
    ];

    const result1 = formatLabelsYaml(labels);
    const result2 = formatLabelsYaml(labels);

    expect(result1).toBe(result2);
  });
});
