import type { PropsWithChildren, ReactElement } from 'react';

import '@/styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: PropsWithChildren): ReactElement {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
