import { join } from 'node:path';

import { createTempTree, type TempTree } from '@williamthorsen/toolbelt.testing/candidate';
import { disposeOnTestFinished } from '@williamthorsen/toolbelt.vitest/candidate';
import { beforeEach, describe, expect, it } from 'vitest';

import { parseChangelogSections, readChangelogSections } from '../readChangelogSections.ts';

const FOOTER =
  '<!-- Generated by release-kit. Do not edit this file. Use .meta/changelog-overrides.json to override entries. -->';

describe(parseChangelogSections, () => {
  it.each([
    ['## 12.0.0 — 2026-09-23', '12.0.0'],
    ['## 1.3.0', '1.3.0'],
    ['## [1.2.3] - 2024-01-01', '1.2.3'],
    ['## v1.2.3', '1.2.3'],
    ['## [v2.0.0-beta.1](https://example.com/compare/v1.0.0...v2.0.0-beta.1) (2024-01-01)', '2.0.0-beta.1'],
  ])('reads the version from %j', (heading, version) => {
    const { versioned } = parseChangelogSections(`${heading}\n\n- item\n`);

    expect(versioned).toStrictEqual([{ version, text: `${heading}\n\n- item` }]);
  });

  it('excludes the header above the first section and the footer comment', () => {
    const content = ['# Changelog', '', 'Intro.', '', '## 1.0.0', '', '- item', '', FOOTER, ''].join('\n');

    const { versioned, unversionedHeadings } = parseChangelogSections(content);

    expect(versioned).toStrictEqual([{ version: '1.0.0', text: '## 1.0.0\n\n- item' }]);
    expect(unversionedHeadings).toStrictEqual([]);
  });

  it('recognizes an earlier wording of the footer comment', () => {
    const content = '## 1.0.0\n\n- item\n\n<!-- Generated by release-kit. Use .changelog-overrides.json. -->\n';

    expect(parseChangelogSections(content).versioned).toStrictEqual([{ version: '1.0.0', text: '## 1.0.0\n\n- item' }]);
  });

  it('keeps deeper headings and internal formatting inside the enclosing section', () => {
    const text = [
      '## 2.0.0',
      '',
      '### Features',
      '',
      '- one',
      '',
      '  indented body',
      '',
      '#### Detail',
      '',
      'Prose.',
    ].join('\n');

    const { versioned } = parseChangelogSections(`${text}\n\n\n## 1.0.0\n\n- item\n`);

    expect(versioned).toStrictEqual([
      { version: '2.0.0', text },
      { version: '1.0.0', text: '## 1.0.0\n\n- item' },
    ]);
  });

  it('treats a `##` line inside a fenced code block as section content', () => {
    const text = ['## 1.0.0', '', '```md', '## 0.9.0', '```'].join('\n');

    expect(parseChangelogSections(`${text}\n`).versioned).toStrictEqual([{ version: '1.0.0', text }]);
  });

  it('reports sections with no version by heading and excludes them from the versioned list', () => {
    const content = ['## Unreleased', '', '- pending', '', '## 1.0.0', '', '- item', '', '## Notes', '', 'x'].join(
      '\n',
    );

    const { versioned, unversionedHeadings } = parseChangelogSections(content);

    expect(versioned.map((section) => section.version)).toStrictEqual(['1.0.0']);
    expect(unversionedHeadings).toStrictEqual(['## Unreleased', '## Notes']);
  });

  it('reads a version-like token in a non-release heading as a version', () => {
    const { versioned } = parseChangelogSections('## Upgrading from 2.0.0\n\nSteps.\n');

    expect(versioned.map((section) => section.version)).toStrictEqual(['2.0.0']);
  });

  it('does not read a version from a longer dotted number or a date', () => {
    const { versioned, unversionedHeadings } = parseChangelogSections('## Build 1.2.3.4\n\n## 2024-01-01\n');

    expect(versioned).toStrictEqual([]);
    expect(unversionedHeadings).toStrictEqual(['## Build 1.2.3.4', '## 2024-01-01']);
  });
});

describe(readChangelogSections, () => {
  let tree: TempTree;

  beforeEach(() => {
    tree = disposeOnTestFinished(createTempTree({}, { prefix: 'read-changelog-sections-' }));
  });

  it('returns empty lists for a missing file', () => {
    expect(readChangelogSections(join(tree.dir, 'CHANGELOG.md'))).toStrictEqual({
      versioned: [],
      unversionedHeadings: [],
    });
  });

  it('reads the sections of an existing file', () => {
    const filePath = tree.write('CHANGELOG.md', '# Changelog\n\n## 1.0.0\n\n- item\n');

    expect(readChangelogSections(filePath).versioned).toStrictEqual([{ version: '1.0.0', text: '## 1.0.0\n\n- item' }]);
  });
});
