import type { WriteResult } from '@williamthorsen/nmr-core';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const mockWriteFileWithCheck = vi.hoisted(() =>
  vi.fn<(path: string, content: string, options: { dryRun: boolean; overwrite: boolean }) => WriteResult>(),
);

vi.mock(import('@williamthorsen/nmr-core'), async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...actual,
    writeFileWithCheck: mockWriteFileWithCheck,
  };
});

import type { ReleasePlan } from '../releasePlan.ts';
import { applyReleasePlan } from '../releasePlan.ts';

describe(applyReleasePlan, () => {
  beforeEach(() => {
    mockWriteFileWithCheck.mockImplementation((filePath: string) => ({ filePath, outcome: 'overwritten' }));
  });

  afterEach(() => {
    mockWriteFileWithCheck.mockReset();
  });

  it('writes content files first, then the summary, then the tags file', () => {
    applyReleasePlan(makePlan());

    expect(writtenPaths()).toStrictEqual([
      'packages/core/package.json',
      'packages/core/CHANGELOG.md',
      'tmp/.release-summary',
      'tmp/.release-tags',
    ]);
  });

  it('omits the summary file when the summary is empty', () => {
    applyReleasePlan(makePlan({ summary: '' }));

    expect(writtenPaths()).not.toContain('tmp/.release-summary');
  });

  it('omits the tags file when the plan releases nothing', () => {
    applyReleasePlan(makePlan({ tags: [] }));

    expect(writtenPaths()).not.toContain('tmp/.release-tags');
  });

  it('writes one tag per line', () => {
    applyReleasePlan(makePlan({ tags: ['core-v1.0.0', 'cli-v2.1.0'] }));

    expect(mockWriteFileWithCheck).toHaveBeenCalledWith('tmp/.release-tags', 'core-v1.0.0\ncli-v2.1.0', {
      dryRun: false,
      overwrite: true,
    });
  });

  it('returns the paths written, in order', () => {
    const written = applyReleasePlan(makePlan());

    expect(written).toStrictEqual([
      'packages/core/package.json',
      'packages/core/CHANGELOG.md',
      'tmp/.release-summary',
      'tmp/.release-tags',
    ]);
  });

  it('if a write fails, names the files already written', () => {
    failOn('packages/core/CHANGELOG.md');

    expect(() => applyReleasePlan(makePlan())).toThrow('1 of 4 files were written:\n  packages/core/package.json');
  });

  it('if a write fails, names the files not written', () => {
    failOn('packages/core/CHANGELOG.md');

    expect(() => applyReleasePlan(makePlan())).toThrow(
      'Not written:\n  packages/core/CHANGELOG.md\n  tmp/.release-summary\n  tmp/.release-tags',
    );
  });

  it('if a write fails, restores the release files it replaced', () => {
    failOn('packages/core/CHANGELOG.md');

    expect(() => applyReleasePlan(makePlan())).toThrow('git restore packages/core/package.json');
  });

  it('if a write fails, deletes the release files it created rather than restoring them', () => {
    failOn('packages/core/CHANGELOG.md', 'ENOSPC: no space left on device', 'created');

    expect(() => applyReleasePlan(makePlan())).toThrow('rm packages/core/package.json');
  });

  it('leaves the tags and summary files out of the recovery commands', () => {
    // They are regenerated by the next `prepare`, and live where `git restore` cannot reach them.
    failOn('tmp/.release-tags');

    const message = captureApplyFailure(makePlan());
    // The recovery block is the message tail, so anchoring the end pins the whole of it.
    expect(message).toMatch(/git restore packages\/core\/package\.json packages\/core\/CHANGELOG\.md$/);
  });

  it('omits the recovery commands when only the handoff files were written', () => {
    failOn('tmp/.release-tags');

    expect(captureApplyFailure(makePlan({ writes: [] }))).not.toContain('Undo the written release files');
  });

  it('if a write fails, reports the underlying error', () => {
    failOn('packages/core/package.json', 'EACCES: permission denied');

    expect(() => applyReleasePlan(makePlan())).toThrow(
      'Failed to write packages/core/package.json: EACCES: permission denied',
    );
  });

  it('if the first write fails, reports that nothing was written', () => {
    failOn('packages/core/package.json');

    expect(() => applyReleasePlan(makePlan())).toThrow(
      'The release was not applied. None of its 4 files were written.',
    );
  });

  it('stops at the first failed write', () => {
    failOn('packages/core/package.json');

    expect(() => applyReleasePlan(makePlan())).toThrow('Failed to write packages/core/package.json');
    expect(writtenPaths()).toStrictEqual(['packages/core/package.json']);
  });
});

// region | Helpers
/** Build a release plan, overriding any field of an otherwise two-file release. */
function makePlan(overrides: Partial<ReleasePlan> = {}): ReleasePlan {
  return {
    writes: [
      { path: 'packages/core/package.json', content: '{ "version": "1.0.0" }\n' },
      { path: 'packages/core/CHANGELOG.md', content: '# Changelog\n' },
    ],
    tags: ['core-v1.0.0'],
    summary: 'core-v1.0.0\n- feat: Add a thing',
    formatCommand: undefined,
    workspaces: [],
    ...overrides,
  };
}

/**
 * Make the write of `path` fail, leaving every other write successful.
 *
 * `successOutcome` decides whether the surviving writes replaced existing files or created them,
 * which is what the recovery commands branch on.
 */
function failOn(
  path: string,
  error = 'ENOSPC: no space left on device',
  successOutcome: WriteResult['outcome'] = 'overwritten',
): void {
  mockWriteFileWithCheck.mockImplementation((filePath: string) =>
    filePath === path ? { filePath, outcome: 'failed', error } : { filePath, outcome: successOutcome },
  );
}

/** Paths passed to `writeFileWithCheck`, in call order. */
function writtenPaths(): string[] {
  return mockWriteFileWithCheck.mock.calls.map(([path]) => path);
}

/** Apply a plan expected to fail, returning the thrown message for multi-part assertions. */
function captureApplyFailure(plan: ReleasePlan): string {
  try {
    applyReleasePlan(plan);
  } catch (error) {
    return error instanceof Error ? error.message : String(error);
  }
  throw new Error('expected applyReleasePlan to throw');
}
// endregion | Helpers
