import { mkdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { renderChangelogMarkdown, writeChangelogMarkdown } from '../renderChangelogMarkdown.ts';
import type { ChangelogEntry } from '../types.ts';

function makeEntry(
  version: string,
  sectionTitle: string,
  items: Array<{ description: string; hash?: string }>,
): ChangelogEntry {
  return {
    version,
    date: '2024-01-01',
    sections: [
      {
        title: sectionTitle,
        audience: 'all',
        items,
      },
    ],
  };
}

describe(renderChangelogMarkdown, () => {
  it('emits the canonical file header at the top', () => {
    const rendered = renderChangelogMarkdown([]);
    expect(
      rendered.startsWith('# Changelog\n\nAll notable changes to this project will be documented in this file.'),
    ).toBe(true);
  });

  it('emits the canonical footer at the bottom', () => {
    const rendered = renderChangelogMarkdown([]);
    expect(
      rendered
        .trimEnd()
        .endsWith(
          '<!-- Generated by release-kit. Do not edit this file. Use .changelog-overrides.json to override entries. -->',
        ),
    ).toBe(true);
  });

  it('terminates with a single trailing newline', () => {
    const rendered = renderChangelogMarkdown([]);
    expect(rendered.endsWith('\n')).toBe(true);
    expect(rendered.endsWith('\n\n')).toBe(false);
  });

  it('renders multiple entries in the order provided', () => {
    const entries: ChangelogEntry[] = [
      makeEntry('2.0.0', 'Features', [{ description: 'Newer feature' }]),
      makeEntry('1.0.0', 'Features', [{ description: 'Older feature' }]),
    ];
    const rendered = renderChangelogMarkdown(entries);
    const newer = rendered.indexOf('2.0.0');
    const older = rendered.indexOf('1.0.0');
    expect(newer).toBeGreaterThanOrEqual(0);
    expect(older).toBeGreaterThan(newer);
  });

  it('emits H2 version + date headings for each entry', () => {
    const entries = [makeEntry('1.0.0', 'Features', [{ description: 'Add widget' }])];
    const rendered = renderChangelogMarkdown(entries);
    expect(rendered).toContain('## 1.0.0 — 2024-01-01');
  });

  it('emits H3 section headings under each entry', () => {
    const entries = [makeEntry('1.0.0', 'Bug fixes', [{ description: 'Fix crash' }])];
    const rendered = renderChangelogMarkdown(entries);
    expect(rendered).toContain('### Bug fixes');
  });

  it('renders each item as a bullet under its section', () => {
    const entries = [makeEntry('1.0.0', 'Features', [{ description: 'Add widget' }])];
    const rendered = renderChangelogMarkdown(entries);
    expect(rendered).toContain('- Add widget');
  });

  it("prefixes breaking items with '🚨 **Breaking:**'", () => {
    const entries: ChangelogEntry[] = [
      {
        version: '1.0.0',
        date: '2024-01-01',
        sections: [
          {
            title: 'Features',
            audience: 'all',
            items: [{ description: 'Redesign API', breaking: true }],
          },
        ],
      },
    ];
    const rendered = renderChangelogMarkdown(entries);
    expect(rendered).toContain('🚨 **Breaking:** Redesign API');
  });

  it('honors the provided sectionOrder', () => {
    const entries: ChangelogEntry[] = [
      {
        version: '1.0.0',
        date: '2024-01-01',
        sections: [
          { title: 'Bug fixes', audience: 'all', items: [{ description: 'Fix' }] },
          { title: 'Features', audience: 'all', items: [{ description: 'Feature' }] },
        ],
      },
    ];
    const rendered = renderChangelogMarkdown(entries, { sectionOrder: ['Features', 'Bug fixes'] });
    const features = rendered.indexOf('### Features');
    const bugFixes = rendered.indexOf('### Bug fixes');
    expect(features).toBeGreaterThanOrEqual(0);
    expect(bugFixes).toBeGreaterThan(features);
  });

  it('renders an empty entry list as just the header and footer', () => {
    const rendered = renderChangelogMarkdown([]);
    // No version headings, no sections.
    expect(rendered).not.toContain('##');
    expect(rendered).toContain('# Changelog');
    expect(rendered).toContain('Generated by release-kit');
  });
});

describe(writeChangelogMarkdown, () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = join(tmpdir(), `test-render-${Date.now()}-${Math.random().toString(36).slice(2)}`);
    mkdirSync(tempDir, { recursive: true });
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('writes the rendered output to ${changelogPath}/CHANGELOG.md', () => {
    const entries = [makeEntry('1.0.0', 'Features', [{ description: 'Add widget' }])];
    const filePath = writeChangelogMarkdown({ changelogPath: tempDir, entries });
    expect(filePath).toBe(`${tempDir}/CHANGELOG.md`);
    const content = readFileSync(filePath, 'utf8');
    expect(content).toContain('## 1.0.0 — 2024-01-01');
    expect(content).toContain('- Add widget');
  });

  it('returns the file path without writing in dry-run mode', () => {
    const entries = [makeEntry('1.0.0', 'Features', [{ description: 'Add widget' }])];
    const filePath = writeChangelogMarkdown({ changelogPath: tempDir, entries, dryRun: true });
    expect(filePath).toBe(`${tempDir}/CHANGELOG.md`);
    expect(() => readFileSync(filePath, 'utf8')).toThrow();
  });

  it('overwrites an existing CHANGELOG.md (regenerative pipeline)', () => {
    // First write — old entry.
    writeChangelogMarkdown({
      changelogPath: tempDir,
      entries: [makeEntry('1.0.0', 'Features', [{ description: 'Old entry' }])],
    });
    // Second write — superset of entries (newest first).
    writeChangelogMarkdown({
      changelogPath: tempDir,
      entries: [
        makeEntry('2.0.0', 'Features', [{ description: 'New entry' }]),
        makeEntry('1.0.0', 'Features', [{ description: 'Old entry' }]),
      ],
    });
    const content = readFileSync(`${tempDir}/CHANGELOG.md`, 'utf8');
    expect(content).toContain('Old entry');
    expect(content).toContain('New entry');
    // Both versions appear, with 2.0.0 above 1.0.0.
    expect(content.indexOf('2.0.0')).toBeLessThan(content.indexOf('1.0.0'));
  });
});
