import type { CanonicalTaxonomy } from './types.ts';

/** The work-type taxonomy shared by every tool that reads or writes the change grammar. */
export const CANONICAL_TAXONOMY: CanonicalTaxonomy = {
  markers: {
    breaking: {
      emoji: '🚨',
      label: 'Breaking',
    },
  },
  tiers: ['public', 'internal', 'process'],
  types: [
    {
      aliases: ['feature'],
      breakingPolicy: 'optional',
      description: 'A change that gives consumers a new capability or extends an existing one.',
      emoji: '🎉',
      key: 'feat',
      label: 'Features',
      tier: 'public',
      trackerLabel: 'feature',
    },
    {
      aliases: [],
      breakingPolicy: 'optional',
      description: 'A change that removes a capability or surface on which consumers depend.',
      emoji: '🪦',
      key: 'drop',
      label: 'Removed',
      tier: 'public',
      trackerLabel: 'removal',
    },
    {
      aliases: [],
      breakingPolicy: 'forbidden',
      description:
        'A change that marks a capability or surface for removal while the capability or surface keeps working.',
      emoji: '🗑️',
      key: 'deprecate',
      label: 'Deprecated',
      tier: 'public',
      trackerLabel: 'deprecation',
    },
    {
      aliases: ['bugfix'],
      breakingPolicy: 'optional',
      description: 'A change that corrects behavior that consumers meet and that differs from what was intended.',
      emoji: '🐛',
      key: 'fix',
      label: 'Bug fixes',
      tier: 'public',
      trackerLabel: 'fix',
    },
    {
      aliases: ['security'],
      breakingPolicy: 'optional',
      description: 'A change that closes a vulnerability or hardens a consumer-facing surface against attack.',
      emoji: '🔒',
      key: 'sec',
      label: 'Security',
      tier: 'public',
      trackerLabel: 'security',
    },
    {
      aliases: ['performance'],
      breakingPolicy: 'optional',
      description:
        'A change that reduces the time, memory, or other resources that consumer-facing work uses, without changing its result.',
      emoji: '⚡',
      key: 'perf',
      label: 'Performance',
      tier: 'public',
      trackerLabel: 'performance',
    },
    {
      aliases: ['utility'],
      breakingPolicy: 'forbidden',
      description:
        'A change that adds, extends, or repairs a capability that consumers do not use directly, such as a helper or an internal module.',
      emoji: '🏗️',
      key: 'internal',
      label: 'Internal features',
      tier: 'internal',
      trackerLabel: 'internal',
    },
    {
      aliases: [],
      breakingPolicy: 'forbidden',
      description: 'A change that restructures existing code without changing its behavior.',
      emoji: '♻️',
      key: 'refactor',
      label: 'Refactoring',
      tier: 'internal',
      trackerLabel: 'refactoring',
    },
    {
      aliases: ['test'],
      breakingPolicy: 'forbidden',
      description:
        'A change confined to tests, test fixtures, or test helpers, including one that unblocks a build or a type check.',
      emoji: '🧪',
      key: 'tests',
      label: 'Tests',
      tier: 'internal',
      trackerLabel: 'tests',
    },
    {
      aliases: [],
      breakingPolicy: 'forbidden',
      description:
        'A change to the tools used to develop the project: build, lint, formatting, and release configuration, and development scripts.',
      emoji: '⚙️',
      key: 'tooling',
      label: 'Tooling',
      tier: 'process',
      trackerLabel: 'tooling',
    },
    {
      aliases: [],
      breakingPolicy: 'forbidden',
      description: 'A change to continuous-integration workflows and their configuration.',
      emoji: '👷',
      key: 'ci',
      label: 'CI',
      tier: 'process',
      trackerLabel: 'ci',
    },
    {
      aliases: ['dep'],
      breakingPolicy: 'forbidden',
      description:
        'A change that adds, removes, or upgrades a dependency, including its lockfile and version-catalog entries.',
      emoji: '📦',
      key: 'deps',
      label: 'Dependencies',
      tier: 'process',
      trackerLabel: 'dependencies',
    },
    {
      aliases: [],
      breakingPolicy: 'forbidden',
      description:
        "A change to guidance on working in the repository itself, such as its `AGENTS.md` or a repo-local skill, or to the repository's agent configuration.",
      emoji: '🤖',
      key: 'ai',
      label: 'Agentic support',
      tier: 'process',
      trackerLabel: 'ai',
    },
    {
      aliases: ['doc'],
      breakingPolicy: 'forbidden',
      description: 'A change to documentation for human readers, such as a README, a guide, or a code comment.',
      emoji: '📚',
      key: 'docs',
      label: 'Documentation',
      tier: 'process',
      trackerLabel: 'documentation',
    },
    {
      aliases: [],
      breakingPolicy: 'forbidden',
      description:
        'A change to formatting alone, such as whitespace or line wrapping, that leaves the content unchanged.',
      emoji: '🎨',
      excludedFromChangelog: true,
      key: 'fmt',
      label: 'Formatting',
      tier: 'process',
      trackerLabel: 'formatting',
    },
  ],
  version: '1.3.0',
};
