/** Generate `src/version.ts` from the package version in `package.json`. */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { z } from 'zod';

const PackageJsonSchema = z.object({ version: z.string() });

const packageDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packageJson = PackageJsonSchema.parse(JSON.parse(readFileSync(path.join(packageDir, 'package.json'), 'utf8')));

const content = `// Generated by config/generateVersion.ts — do not edit\nexport const VERSION = '${packageJson.version}';\n`;
writeFileSync(path.join(packageDir, 'src', 'version.ts'), content);
