import { existsSync, readFileSync } from 'node:fs';

import semver from 'semver';

import type { ChangelogEntry, ChangelogPreservation } from './types.ts';

/** A `##` section of a `CHANGELOG.md` whose heading names a version. */
export interface VersionedMarkdownSection {
  version: string;
  /** The section as written, heading included, with trailing blank lines trimmed. */
  text: string;
}

/** The `##` sections of a `CHANGELOG.md`, split by whether their heading names a version. */
export interface ChangelogMarkdownSections {
  versioned: VersionedMarkdownSection[];
  /** Headings of the `##` sections that name no version, as written. */
  unversionedHeadings: string[];
}

/**
 * Plans which sections of the existing `CHANGELOG.md` at `changelogFile` to keep when the file is regenerated from
 * `entries`: every versioned section whose version no entry has. Also returns what to report about the file, or
 * undefined when nothing was kept and nothing was dropped.
 */
export function planPreservedSections(
  changelogFile: string,
  entries: readonly ChangelogEntry[],
): { sections: VersionedMarkdownSection[]; preservation: ChangelogPreservation | undefined } {
  const { versioned, unversionedHeadings } = readChangelogSections(changelogFile);
  const renderedVersions = new Set(entries.map((entry) => entry.version));
  const sections = versioned.filter((section) => !renderedVersions.has(section.version));
  if (sections.length === 0 && unversionedHeadings.length === 0) {
    return { sections, preservation: undefined };
  }
  return {
    sections,
    preservation: {
      file: changelogFile,
      preservedVersions: sections.map((section) => section.version),
      droppedUnversionedHeadings: unversionedHeadings,
    },
  };
}

/**
 * Reads the `##` sections of the `CHANGELOG.md` at `filePath`, excluding the header above the first section and the
 * release-kit footer comment. A missing file has no sections.
 */
export function readChangelogSections(filePath: string): ChangelogMarkdownSections {
  if (!existsSync(filePath)) {
    return { versioned: [], unversionedHeadings: [] };
  }
  return parseChangelogSections(readFileSync(filePath, 'utf8'));
}

/**
 * Splits `CHANGELOG.md` content at its `##` headings. A section runs to the next `##` heading or the release-kit
 * footer comment; `###` and deeper headings, and any heading inside a fenced code block, belong to the enclosing
 * section.
 */
export function parseChangelogSections(content: string): ChangelogMarkdownSections {
  const sections: Array<{ heading: string; lines: string[] }> = [];
  let current: { heading: string; lines: string[] } | undefined;
  let fence: string | undefined;

  for (const line of content.split(/\r?\n/)) {
    if (fence === undefined) {
      if (FOOTER_PATTERN.test(line)) {
        current = undefined;
        continue;
      }
      if (SECTION_HEADING_PATTERN.test(line)) {
        current = { heading: line.trimEnd(), lines: [] };
        sections.push(current);
      }
    }
    fence = updateFence(fence, line);
    current?.lines.push(line);
  }

  const versioned: VersionedMarkdownSection[] = [];
  const unversionedHeadings: string[] = [];
  for (const { heading, lines } of sections) {
    const version = extractHeadingVersion(heading);
    if (version === undefined) {
      unversionedHeadings.push(heading);
    } else {
      versioned.push({ version, text: trimTrailingBlankLines(lines).join('\n') });
    }
  }

  return { versioned, unversionedHeadings };
}

// region | Helpers

/** Matches the comment that release-kit writes at the end of a generated `CHANGELOG.md`, in any of its wordings. */
const FOOTER_PATTERN = /^<!-- Generated by release-kit\b/;

/** Matches a level-2 ATX heading; `###` and deeper do not match. */
const SECTION_HEADING_PATTERN = /^## /;

/** Matches the opening or closing marker of a fenced code block. */
const FENCE_PATTERN = /^ {0,3}(`{3,}|~{3,})/;

/**
 * Matches the first SemVer token in a heading, with an optional leading `v`. The lookarounds keep a token from
 * starting or ending inside a longer dotted number or word.
 */
const HEADING_VERSION_PATTERN =
  /(?<![\w.])v?(\d+\.\d+\.\d+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?)(?!\.?\d)/;

/** Returns the version named by a `##` heading, or undefined when it names none. */
function extractHeadingVersion(heading: string): string | undefined {
  const token = HEADING_VERSION_PATTERN.exec(heading)?.[1];
  if (token === undefined) return undefined;
  return semver.valid(token) ?? undefined;
}

/** Returns trailing blank lines removed from `lines`. */
function trimTrailingBlankLines(lines: readonly string[]): string[] {
  let end = lines.length;
  while (end > 0 && lines[end - 1]?.trim() === '') {
    end--;
  }
  return lines.slice(0, end);
}

/** Returns the open fence marker after `line`: opened, closed by a matching marker, or unchanged. */
function updateFence(fence: string | undefined, line: string): string | undefined {
  const marker = FENCE_PATTERN.exec(line)?.[1];
  if (marker === undefined) return fence;
  if (fence === undefined) return marker;
  return marker[0] === fence[0] && marker.length >= fence.length ? undefined : fence;
}

// endregion | Helpers
