import { renderReleaseNotesMulti } from './renderReleaseNotes.ts';
import type { ChangelogEntry } from './types.ts';

/** Top-of-file header emitted at the start of every generated `CHANGELOG.md`. */
const CHANGELOG_HEADER = `# Changelog

All notable changes to this project will be documented in this file.`;

/**
 * Bottom-of-file footer emitted after all version content. Replaces the
 * `<!-- generated by git-cliff -->` comment that the cliff body template used to emit.
 * Informational only — no logic depends on its presence.
 */
const CHANGELOG_FOOTER = `<!-- Generated by release-kit. Do not edit this file. Use .meta/changelog-overrides.json to override entries. -->`;

/** Options for `renderChangelogMarkdown`. */
export interface RenderChangelogMarkdownOptions {
  /** Section titles in canonical order; passed through to `renderReleaseNotesMulti`. */
  sectionOrder?: string[];
}

/**
 * Render `ChangelogEntry[]` into a complete `CHANGELOG.md`-shaped string.
 *
 * Format:
 *   `# Changelog`
 *   blank line
 *   `All notable changes …`
 *   blank line
 *   per-entry sections (delegated to `renderReleaseNotesMulti`)
 *   blank line
 *   footer comment
 *
 * Entries are rendered in the order provided; the caller sorts (typically newest-first via
 * `changelogJsonFile`'s SemVer-aware comparator).
 */
export function renderChangelogMarkdown(entries: ChangelogEntry[], options?: RenderChangelogMarkdownOptions): string {
  const body = renderReleaseNotesMulti(entries, options);
  const trimmedBody = body.trimEnd();

  const parts = [CHANGELOG_HEADER];
  if (trimmedBody.length > 0) {
    parts.push(trimmedBody);
  }
  parts.push(CHANGELOG_FOOTER);
  return parts.join('\n\n') + '\n';
}
