import { compareVersionsDescending } from './compareVersions.ts';
import type { VersionedMarkdownSection } from './readChangelogSections.ts';
import { renderReleaseNotesSingle } from './renderReleaseNotes.ts';
import type { ChangelogEntry } from './types.ts';

/** Top-of-file header emitted at the start of every generated `CHANGELOG.md`. */
const CHANGELOG_HEADER = `# Changelog

All notable changes to this project will be documented in this file.`;

/** Bottom-of-file footer emitted after all version content. Informational only — no logic depends on its presence. */
const CHANGELOG_FOOTER = `<!-- Generated by release-kit. Do not edit this file. Use .meta/changelog-overrides.json to override entries. -->`;

/** Options for `renderChangelogMarkdown`. */
export interface RenderChangelogMarkdownOptions {
  /** Section titles in canonical order; passed through to `renderReleaseNotesSingle`. */
  sectionOrder?: string[];
  /**
   * Sections of the existing `CHANGELOG.md` to keep verbatim, interleaved by version among the rendered entries. No
   * section's version may also be an entry's version.
   */
  preservedSections?: readonly VersionedMarkdownSection[];
}

/**
 * Render `ChangelogEntry[]` into a complete `CHANGELOG.md`-shaped string.
 *
 * Format:
 *   `# Changelog`
 *   blank line
 *   `All notable changes …`
 *   blank line
 *   per-entry sections (delegated to `renderReleaseNotesSingle`), with preserved sections interleaved by version
 *   blank line
 *   footer comment
 *
 * Entries are rendered in the order provided; the caller sorts (typically newest-first via
 * `compareVersionsDescending`).
 */
export function renderChangelogMarkdown(entries: ChangelogEntry[], options?: RenderChangelogMarkdownOptions): string {
  const sections = interleavePreservedSections(
    entries.map((entry) => ({ version: entry.version, text: renderReleaseNotesSingle(entry, options) })),
    options?.preservedSections ?? [],
  );
  const body = sections
    .map((part) => part.text)
    .filter((text) => text.length > 0)
    .join('\n');
  const trimmedBody = body.trimEnd();

  const parts = [CHANGELOG_HEADER];
  if (trimmedBody.length > 0) {
    parts.push(trimmedBody);
  }
  parts.push(CHANGELOG_FOOTER);
  return parts.join('\n\n') + '\n';
}

// region | Helpers

/**
 * Returns the rendered parts, in their given order, with each preserved section placed before the first part whose
 * version it is newer than.
 */
function interleavePreservedSections(
  rendered: readonly VersionedMarkdownSection[],
  preserved: readonly VersionedMarkdownSection[],
): VersionedMarkdownSection[] {
  // eslint-disable-next-line unicorn/no-array-sort -- spread already creates a fresh copy; toSorted requires Node >=20
  const sorted = [...preserved].sort((a, b) => compareVersionsDescending(a.version, b.version));
  const pending = sorted.map(withTrailingNewline);
  const result: VersionedMarkdownSection[] = [];
  let index = 0;
  for (const part of rendered) {
    let section = pending[index];
    while (section !== undefined && compareVersionsDescending(section.version, part.version) < 0) {
      result.push(section);
      index++;
      section = pending[index];
    }
    result.push(part);
  }
  result.push(...pending.slice(index));
  return result;
}

/** Terminates a preserved section's text with a newline, as a rendered entry's text is. */
function withTrailingNewline(section: VersionedMarkdownSection): VersionedMarkdownSection {
  return { version: section.version, text: `${section.text}\n` };
}

// endregion | Helpers
