import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import { renderReleaseNotesMulti } from './renderReleaseNotes.ts';
import type { ChangelogEntry } from './types.ts';

/** Top-of-file header emitted at the start of every generated `CHANGELOG.md`. */
const CHANGELOG_HEADER = `# Changelog

All notable changes to this project will be documented in this file.`;

/**
 * Bottom-of-file footer emitted after all version content. Replaces the
 * `<!-- generated by git-cliff -->` comment that the cliff body template used to emit.
 * Informational only — no logic depends on its presence.
 */
const CHANGELOG_FOOTER = `<!-- Generated by release-kit. Do not edit this file. Use .changelog-overrides.json to override entries. -->`;

/** Options for `renderChangelogMarkdown`. */
export interface RenderChangelogMarkdownOptions {
  /** Section titles in canonical order; passed through to `renderReleaseNotesMulti`. */
  sectionOrder?: string[];
}

/**
 * Render `ChangelogEntry[]` into a complete `CHANGELOG.md`-shaped string.
 *
 * Format:
 *   `# Changelog`
 *   blank line
 *   `All notable changes …`
 *   blank line
 *   per-entry sections (delegated to `renderReleaseNotesMulti`)
 *   blank line
 *   footer comment
 *
 * Entries are rendered in the order provided; the caller sorts (typically newest-first via
 * `changelogJsonFile`'s SemVer-aware comparator).
 */
export function renderChangelogMarkdown(entries: ChangelogEntry[], options?: RenderChangelogMarkdownOptions): string {
  const body = renderReleaseNotesMulti(entries, options);
  const trimmedBody = body.trimEnd();

  const parts = [CHANGELOG_HEADER];
  if (trimmedBody.length > 0) {
    parts.push(trimmedBody);
  }
  parts.push(CHANGELOG_FOOTER);
  return parts.join('\n\n') + '\n';
}

/** Parameters for writing a rendered changelog to disk. */
export interface WriteChangelogMarkdownParams {
  changelogPath: string;
  entries: ChangelogEntry[];
  sectionOrder?: string[];
  dryRun?: boolean;
}

/**
 * Render `entries` and write the result to `${changelogPath}/CHANGELOG.md`.
 *
 * Replaces the cliff `--output` invocation that the previous `generateChangelog` helper
 * shelled out to. The file is overwritten unconditionally — historical preservation is
 * carried by the `changelog.json` artifact, which is the SSOT for entries.
 *
 * Returns the file path written. In dry-run mode performs no I/O but still returns the path.
 */
export function writeChangelogMarkdown(params: WriteChangelogMarkdownParams): string {
  const { changelogPath, entries, sectionOrder, dryRun = false } = params;
  const filePath = `${changelogPath}/CHANGELOG.md`;

  if (dryRun) {
    return filePath;
  }

  const rendered = renderChangelogMarkdown(entries, sectionOrder !== undefined ? { sectionOrder } : undefined);
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, rendered, 'utf8');
  return filePath;
}
